// Background Library Configuration for Virtual Try-On V2
// Auto-generated by scripts/generate-background-library.ts
// Total: 153 backgrounds (Girl: 119, Boy: 19, Kid: 15)

import type {
  BackgroundLibrary,
  BackgroundPoseItem,
  BackgroundCategory
} from '../types/background';

/**
 * 背景图片基础路径
 * 实际部署时需要将图片复制到 public/backgrounds 目录
 */
export const BACKGROUND_BASE_PATH = '/backgrounds';

/**
 * 干净背景（人物已移除）的基础路径
 * 用于 V3 单轮生成模式
 */
export const CLEAN_BACKGROUND_BASE_PATH = '/backgrounds-clean';

/**
 * 从原图URL生成干净背景URL
 * @param originalUrl 原图URL (e.g., '/backgrounds/girl/photo.jpg')
 * @returns 干净背景URL (e.g., '/backgrounds-clean/girl/photo.jpg')
 */
export function getCleanBackgroundUrl(originalUrl: string): string {
  // 将原图路径转换为干净背景路径，并统一使用 .jpg 扩展名
  return originalUrl
    .replace(BACKGROUND_BASE_PATH, CLEAN_BACKGROUND_BASE_PATH)
    .replace(/\.(JPG|JPEG|PNG|jpeg|png)$/i, '.jpg');
}

/**
 * 静态背景库配置
 * 图片来源于 background&pose 文件夹
 */
export const BACKGROUND_LIBRARY: BackgroundLibrary = {
  girl: [
    {
      id: 'girl-001',
      name: '女生背景 1',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/010A7117.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/010A7117.jpg`,
    },
    {
      id: 'girl-002',
      name: '女生背景 2',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/010A8096.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/010A8096.jpg`,
    },
    {
      id: 'girl-003',
      name: '女生背景 3',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/0R1A0294.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/0R1A0294.jpg`,
    },
    {
      id: 'girl-004',
      name: '女生背景 4',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/0R1A0352.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/0R1A0352.jpg`,
    },
    {
      id: 'girl-005',
      name: '女生背景 5',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/0R1A3323.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/0R1A3323.jpg`,
    },
    {
      id: 'girl-006',
      name: '女生背景 6',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/0R1A3666.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/0R1A3666.jpg`,
    },
    {
      id: 'girl-007',
      name: '女生背景 7',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/1202416_(2).jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/1202416_(2).jpg`,
    },
    {
      id: 'girl-008',
      name: '女生背景 8',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/1202438.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/1202438.jpg`,
    },
    {
      id: 'girl-009',
      name: '女生背景 9',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/13406619282679822.jpeg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/13406619282679822.jpg`,
    },
    {
      id: 'girl-010',
      name: '女生背景 10',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/13407320388772820.jpeg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/13407320388772820.jpg`,
    },
    {
      id: 'girl-011',
      name: '女生背景 11',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/13407484978299363.jpeg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/13407484978299363.jpg`,
    },
    {
      id: 'girl-012',
      name: '女生背景 12',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/13407485242664986.jpeg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/13407485242664986.jpg`,
    },
    {
      id: 'girl-013',
      name: '女生背景 13',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/13407485307123564.jpeg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/13407485307123564.jpg`,
    },
    {
      id: 'girl-014',
      name: '女生背景 14',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/13407485367880907.jpeg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/13407485367880907.jpg`,
    },
    {
      id: 'girl-015',
      name: '女生背景 15',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/13407485837956742.jpeg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/13407485837956742.jpg`,
    },
    {
      id: 'girl-016',
      name: '女生背景 16',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/202401-17.JPG`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/202401-17.jpg`,
    },
    {
      id: 'girl-017',
      name: '女生背景 17',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/202401-27.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/202401-27.jpg`,
    },
    {
      id: 'girl-018',
      name: '女生背景 18',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/202401-32.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/202401-32.jpg`,
    },
    {
      id: 'girl-019',
      name: '女生背景 19',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/202401-6.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/202401-6.jpg`,
    },
    {
      id: 'girl-020',
      name: '女生背景 20',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/202401.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/202401.jpg`,
    },
    {
      id: 'girl-021',
      name: '女生背景 21',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/2065f3080ff2ed2413235577b8054de5.jpeg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/2065f3080ff2ed2413235577b8054de5.jpg`,
    },
    {
      id: 'girl-022',
      name: '女生背景 22',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/2b335e79282fa85e3822623a27ec6407.JPG`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/2b335e79282fa85e3822623a27ec6407.jpg`,
    },
    {
      id: 'girl-023',
      name: '女生背景 23',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/6f569fc513ff37d21754676dd50628f8.jpeg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/6f569fc513ff37d21754676dd50628f8.jpg`,
    },
    {
      id: 'girl-024',
      name: '女生背景 24',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/881f67cfca73271e3cce6fc9588ffad0.jpeg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/881f67cfca73271e3cce6fc9588ffad0.jpg`,
    },
    {
      id: 'girl-025',
      name: '女生背景 25',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/8fc9a9c552ecb1fbf9fbf6c9bf2df69c.JPG`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/8fc9a9c552ecb1fbf9fbf6c9bf2df69c.jpg`,
    },
    {
      id: 'girl-026',
      name: '女生背景 26',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC00116.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC00116.jpg`,
    },
    {
      id: 'girl-027',
      name: '女生背景 27',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC00674.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC00674.jpg`,
    },
    {
      id: 'girl-028',
      name: '女生背景 28',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC00735.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC00735.jpg`,
    },
    {
      id: 'girl-029',
      name: '女生背景 29',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC00744.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC00744.jpg`,
    },
    {
      id: 'girl-030',
      name: '女生背景 30',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC00786.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC00786.jpg`,
    },
    {
      id: 'girl-031',
      name: '女生背景 31',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC00834.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC00834.jpg`,
    },
    {
      id: 'girl-032',
      name: '女生背景 32',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC00966.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC00966.jpg`,
    },
    {
      id: 'girl-033',
      name: '女生背景 33',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC01064.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC01064.jpg`,
    },
    {
      id: 'girl-034',
      name: '女生背景 34',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC01414.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC01414.jpg`,
    },
    {
      id: 'girl-035',
      name: '女生背景 35',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC01591.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC01591.jpg`,
    },
    {
      id: 'girl-036',
      name: '女生背景 36',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC01699.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC01699.jpg`,
    },
    {
      id: 'girl-037',
      name: '女生背景 37',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC02281.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC02281.jpg`,
    },
    {
      id: 'girl-038',
      name: '女生背景 38',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC02294.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC02294.jpg`,
    },
    {
      id: 'girl-039',
      name: '女生背景 39',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC02295.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC02295.jpg`,
    },
    {
      id: 'girl-040',
      name: '女生背景 40',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC02309.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC02309.jpg`,
    },
    {
      id: 'girl-041',
      name: '女生背景 41',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC02313.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC02313.jpg`,
    },
    {
      id: 'girl-042',
      name: '女生背景 42',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC02412.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC02412.jpg`,
    },
    {
      id: 'girl-043',
      name: '女生背景 43',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC02692.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC02692.jpg`,
    },
    {
      id: 'girl-044',
      name: '女生背景 44',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC02846.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC02846.jpg`,
    },
    {
      id: 'girl-045',
      name: '女生背景 45',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC03054.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC03054.jpg`,
    },
    {
      id: 'girl-046',
      name: '女生背景 46',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC03139.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC03139.jpg`,
    },
    {
      id: 'girl-047',
      name: '女生背景 47',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC03613-2.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC03613-2.jpg`,
    },
    {
      id: 'girl-048',
      name: '女生背景 48',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC03728.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC03728.jpg`,
    },
    {
      id: 'girl-049',
      name: '女生背景 49',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC04072.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC04072.jpg`,
    },
    {
      id: 'girl-050',
      name: '女生背景 50',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC04254.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC04254.jpg`,
    },
    {
      id: 'girl-051',
      name: '女生背景 51',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC04371.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC04371.jpg`,
    },
    {
      id: 'girl-052',
      name: '女生背景 52',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC04405.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC04405.jpg`,
    },
    {
      id: 'girl-053',
      name: '女生背景 53',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC04563.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC04563.jpg`,
    },
    {
      id: 'girl-054',
      name: '女生背景 54',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC04590.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC04590.jpg`,
    },
    {
      id: 'girl-055',
      name: '女生背景 55',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC04598.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC04598.jpg`,
    },
    {
      id: 'girl-056',
      name: '女生背景 56',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC04935.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC04935.jpg`,
    },
    {
      id: 'girl-057',
      name: '女生背景 57',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC04964.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC04964.jpg`,
    },
    {
      id: 'girl-058',
      name: '女生背景 58',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC05173.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC05173.jpg`,
    },
    {
      id: 'girl-059',
      name: '女生背景 59',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC05206.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC05206.jpg`,
    },
    {
      id: 'girl-060',
      name: '女生背景 60',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC05311.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC05311.jpg`,
    },
    {
      id: 'girl-061',
      name: '女生背景 61',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC05514.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC05514.jpg`,
    },
    {
      id: 'girl-062',
      name: '女生背景 62',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC05641.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC05641.jpg`,
    },
    {
      id: 'girl-063',
      name: '女生背景 63',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC05713.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC05713.jpg`,
    },
    {
      id: 'girl-064',
      name: '女生背景 64',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC05775.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC05775.jpg`,
    },
    {
      id: 'girl-065',
      name: '女生背景 65',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC05776.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC05776.jpg`,
    },
    {
      id: 'girl-066',
      name: '女生背景 66',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC06275.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC06275.jpg`,
    },
    {
      id: 'girl-067',
      name: '女生背景 67',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC0643511.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC0643511.jpg`,
    },
    {
      id: 'girl-068',
      name: '女生背景 68',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC06503.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC06503.jpg`,
    },
    {
      id: 'girl-069',
      name: '女生背景 69',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC06730.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC06730.jpg`,
    },
    {
      id: 'girl-070',
      name: '女生背景 70',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC06799.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC06799.jpg`,
    },
    {
      id: 'girl-071',
      name: '女生背景 71',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC07278.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC07278.jpg`,
    },
    {
      id: 'girl-072',
      name: '女生背景 72',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC07490-.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC07490-.jpg`,
    },
    {
      id: 'girl-073',
      name: '女生背景 73',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC07507.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC07507.jpg`,
    },
    {
      id: 'girl-074',
      name: '女生背景 74',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC07610.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC07610.jpg`,
    },
    {
      id: 'girl-075',
      name: '女生背景 75',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC07679.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC07679.jpg`,
    },
    {
      id: 'girl-076',
      name: '女生背景 76',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC07704-已增强-降噪.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC07704-已增强-降噪.jpg`,
    },
    {
      id: 'girl-077',
      name: '女生背景 77',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC07769.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC07769.jpg`,
    },
    {
      id: 'girl-078',
      name: '女生背景 78',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC07795-已增强-降噪.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC07795-已增强-降噪.jpg`,
    },
    {
      id: 'girl-079',
      name: '女生背景 79',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC07922.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC07922.jpg`,
    },
    {
      id: 'girl-080',
      name: '女生背景 80',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC08048.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC08048.jpg`,
    },
    {
      id: 'girl-081',
      name: '女生背景 81',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC08219.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC08219.jpg`,
    },
    {
      id: 'girl-082',
      name: '女生背景 82',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC08355.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC08355.jpg`,
    },
    {
      id: 'girl-083',
      name: '女生背景 83',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC08367.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC08367.jpg`,
    },
    {
      id: 'girl-084',
      name: '女生背景 84',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC08396.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC08396.jpg`,
    },
    {
      id: 'girl-085',
      name: '女生背景 85',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC08538.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC08538.jpg`,
    },
    {
      id: 'girl-086',
      name: '女生背景 86',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC08780.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC08780.jpg`,
    },
    {
      id: 'girl-087',
      name: '女生背景 87',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC08843.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC08843.jpg`,
    },
    {
      id: 'girl-088',
      name: '女生背景 88',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC08953.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC08953.jpg`,
    },
    {
      id: 'girl-089',
      name: '女生背景 89',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC09394.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC09394.jpg`,
    },
    {
      id: 'girl-090',
      name: '女生背景 90',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC09989.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC09989.jpg`,
    },
    {
      id: 'girl-091',
      name: '女生背景 91',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSC09996.JPG`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSC09996.jpg`,
    },
    {
      id: 'girl-092',
      name: '女生背景 92',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSCF3235.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSCF3235.jpg`,
    },
    {
      id: 'girl-093',
      name: '女生背景 93',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSCF6562.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSCF6562.jpg`,
    },
    {
      id: 'girl-094',
      name: '女生背景 94',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/DSCF7550.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/DSCF7550.jpg`,
    },
    {
      id: 'girl-095',
      name: '女生背景 95',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/IMG_0189.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/IMG_0189.jpg`,
    },
    {
      id: 'girl-096',
      name: '女生背景 96',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/IMG_0437.JPG`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/IMG_0437.jpg`,
    },
    {
      id: 'girl-097',
      name: '女生背景 97',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/IMG_0542.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/IMG_0542.jpg`,
    },
    {
      id: 'girl-098',
      name: '女生背景 98',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/IMG_1151-Exposure.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/IMG_1151-Exposure.jpg`,
    },
    {
      id: 'girl-099',
      name: '女生背景 99',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/IMG_1512.JPG`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/IMG_1512.jpg`,
    },
    {
      id: 'girl-100',
      name: '女生背景 100',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/IMG_2740.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/IMG_2740.jpg`,
    },
    {
      id: 'girl-101',
      name: '女生背景 101',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/IMG_4708.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/IMG_4708.jpg`,
    },
    {
      id: 'girl-102',
      name: '女生背景 102',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/IMG_5977.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/IMG_5977.jpg`,
    },
    {
      id: 'girl-103',
      name: '女生背景 103',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/IMG_7827.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/IMG_7827.jpg`,
    },
    {
      id: 'girl-104',
      name: '女生背景 104',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/IMG_9060.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/IMG_9060.jpg`,
    },
    {
      id: 'girl-105',
      name: '女生背景 105',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/IMG_9337.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/IMG_9337.jpg`,
    },
    {
      id: 'girl-106',
      name: '女生背景 106',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/IMG_9480.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/IMG_9480.jpg`,
    },
    {
      id: 'girl-107',
      name: '女生背景 107',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/WeChat 圖片_20211211215603.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/WeChat 圖片_20211211215603.jpg`,
    },
    {
      id: 'girl-108',
      name: '女生背景 108',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/_DSC9933.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/_DSC9933.jpg`,
    },
    {
      id: 'girl-109',
      name: '女生背景 109',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/e417b088fe9332f5380863ca8a525389.JPG`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/e417b088fe9332f5380863ca8a525389.jpg`,
    },
    {
      id: 'girl-110',
      name: '女生背景 110',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/e6fad8873e2aafd03637b1879efdfd06.jpeg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/e6fad8873e2aafd03637b1879efdfd06.jpg`,
    },
    {
      id: 'girl-111',
      name: '女生背景 111',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/ea39d394c113a659d1b337144971e560.JPG`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/ea39d394c113a659d1b337144971e560.jpg`,
    },
    {
      id: 'girl-112',
      name: '女生背景 112',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/圖片_20240218150505.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/圖片_20240218150505.jpg`,
    },
    {
      id: 'girl-113',
      name: '女生背景 113',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/截屏2025-07-13 13.28.57.png`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/截屏2025-07-13 13.28.57.jpg`,
    },
    {
      id: 'girl-114',
      name: '女生背景 114',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/截屏2025-07-13 13.51.09.png`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/截屏2025-07-13 13.51.09.jpg`,
    },
    {
      id: 'girl-115',
      name: '女生背景 115',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/截屏2025-07-13 13.52.46.png`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/截屏2025-07-13 13.52.46.jpg`,
    },
    {
      id: 'girl-116',
      name: '女生背景 116',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/截屏2025-07-13 14.21.06.png`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/截屏2025-07-13 14.21.06.jpg`,
    },
    {
      id: 'girl-117',
      name: '女生背景 117',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/截屏2025-07-13 14.21.22.png`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/截屏2025-07-13 14.21.22.jpg`,
    },
    {
      id: 'girl-118',
      name: '女生背景 118',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/截屏2025-07-30 15.55.05.png`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/截屏2025-07-30 15.55.05.jpg`,
    },
    {
      id: 'girl-119',
      name: '女生背景 119',
      category: 'girl',
      imageUrl: `${BACKGROUND_BASE_PATH}/girl/被大家喜欢真是太幸福太开心啦！_6_KeKe=Ariel_来自小红书网页版.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/girl/被大家喜欢真是太幸福太开心啦！_6_KeKe=Ariel_来自小红书网页版.jpg`,
    }
  ],
  boy: [
    {
      id: 'boy-001',
      name: '男生背景 1',
      category: 'boy',
      imageUrl: `${BACKGROUND_BASE_PATH}/boy/0R1A3793.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/boy/0R1A3793.jpg`,
    },
    {
      id: 'boy-002',
      name: '男生背景 2',
      category: 'boy',
      imageUrl: `${BACKGROUND_BASE_PATH}/boy/202401-3.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/boy/202401-3.jpg`,
    },
    {
      id: 'boy-003',
      name: '男生背景 3',
      category: 'boy',
      imageUrl: `${BACKGROUND_BASE_PATH}/boy/DSC01294.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/boy/DSC01294.jpg`,
    },
    {
      id: 'boy-004',
      name: '男生背景 4',
      category: 'boy',
      imageUrl: `${BACKGROUND_BASE_PATH}/boy/DSC02308.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/boy/DSC02308.jpg`,
    },
    {
      id: 'boy-005',
      name: '男生背景 5',
      category: 'boy',
      imageUrl: `${BACKGROUND_BASE_PATH}/boy/DSC02346.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/boy/DSC02346.jpg`,
    },
    {
      id: 'boy-006',
      name: '男生背景 6',
      category: 'boy',
      imageUrl: `${BACKGROUND_BASE_PATH}/boy/DSC02389.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/boy/DSC02389.jpg`,
    },
    {
      id: 'boy-007',
      name: '男生背景 7',
      category: 'boy',
      imageUrl: `${BACKGROUND_BASE_PATH}/boy/DSC05648.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/boy/DSC05648.jpg`,
    },
    {
      id: 'boy-008',
      name: '男生背景 8',
      category: 'boy',
      imageUrl: `${BACKGROUND_BASE_PATH}/boy/DSC06732-2.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/boy/DSC06732-2.jpg`,
    },
    {
      id: 'boy-009',
      name: '男生背景 9',
      category: 'boy',
      imageUrl: `${BACKGROUND_BASE_PATH}/boy/DSC09824.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/boy/DSC09824.jpg`,
    },
    {
      id: 'boy-010',
      name: '男生背景 10',
      category: 'boy',
      imageUrl: `${BACKGROUND_BASE_PATH}/boy/DSCF7922.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/boy/DSCF7922.jpg`,
    },
    {
      id: 'boy-011',
      name: '男生背景 11',
      category: 'boy',
      imageUrl: `${BACKGROUND_BASE_PATH}/boy/IMG_1616.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/boy/IMG_1616.jpg`,
    },
    {
      id: 'boy-012',
      name: '男生背景 12',
      category: 'boy',
      imageUrl: `${BACKGROUND_BASE_PATH}/boy/IMG_1804-2.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/boy/IMG_1804-2.jpg`,
    },
    {
      id: 'boy-013',
      name: '男生背景 13',
      category: 'boy',
      imageUrl: `${BACKGROUND_BASE_PATH}/boy/IMG_6023.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/boy/IMG_6023.jpg`,
    },
    {
      id: 'boy-014',
      name: '男生背景 14',
      category: 'boy',
      imageUrl: `${BACKGROUND_BASE_PATH}/boy/IMG_7177.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/boy/IMG_7177.jpg`,
    },
    {
      id: 'boy-015',
      name: '男生背景 15',
      category: 'boy',
      imageUrl: `${BACKGROUND_BASE_PATH}/boy/_DSC0049.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/boy/_DSC0049.jpg`,
    },
    {
      id: 'boy-016',
      name: '男生背景 16',
      category: 'boy',
      imageUrl: `${BACKGROUND_BASE_PATH}/boy/_DSC5885.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/boy/_DSC5885.jpg`,
    },
    {
      id: 'boy-017',
      name: '男生背景 17',
      category: 'boy',
      imageUrl: `${BACKGROUND_BASE_PATH}/boy/_DSC7791.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/boy/_DSC7791.jpg`,
    },
    {
      id: 'boy-018',
      name: '男生背景 18',
      category: 'boy',
      imageUrl: `${BACKGROUND_BASE_PATH}/boy/截屏2025-07-13 13.29.45.png`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/boy/截屏2025-07-13 13.29.45.jpg`,
    },
    {
      id: 'boy-019',
      name: '男生背景 19',
      category: 'boy',
      imageUrl: `${BACKGROUND_BASE_PATH}/boy/截屏2025-07-13 13.51.53.png`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/boy/截屏2025-07-13 13.51.53.jpg`,
    }
  ],
  kid: [
    {
      id: 'kid-001',
      name: '儿童背景 1',
      category: 'kid',
      imageUrl: `${BACKGROUND_BASE_PATH}/kid/0R1A0203.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/kid/0R1A0203.jpg`,
    },
    {
      id: 'kid-002',
      name: '儿童背景 2',
      category: 'kid',
      imageUrl: `${BACKGROUND_BASE_PATH}/kid/0R1A3831.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/kid/0R1A3831.jpg`,
    },
    {
      id: 'kid-003',
      name: '儿童背景 3',
      category: 'kid',
      imageUrl: `${BACKGROUND_BASE_PATH}/kid/13406619059877009.jpeg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/kid/13406619059877009.jpg`,
    },
    {
      id: 'kid-004',
      name: '儿童背景 4',
      category: 'kid',
      imageUrl: `${BACKGROUND_BASE_PATH}/kid/13406619081837480.jpeg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/kid/13406619081837480.jpg`,
    },
    {
      id: 'kid-005',
      name: '儿童背景 5',
      category: 'kid',
      imageUrl: `${BACKGROUND_BASE_PATH}/kid/13406798622888412.jpeg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/kid/13406798622888412.jpg`,
    },
    {
      id: 'kid-006',
      name: '儿童背景 6',
      category: 'kid',
      imageUrl: `${BACKGROUND_BASE_PATH}/kid/13406798638726990.jpeg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/kid/13406798638726990.jpg`,
    },
    {
      id: 'kid-007',
      name: '儿童背景 7',
      category: 'kid',
      imageUrl: `${BACKGROUND_BASE_PATH}/kid/13407230080958538.jpeg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/kid/13407230080958538.jpg`,
    },
    {
      id: 'kid-008',
      name: '儿童背景 8',
      category: 'kid',
      imageUrl: `${BACKGROUND_BASE_PATH}/kid/13407230104361955.jpeg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/kid/13407230104361955.jpg`,
    },
    {
      id: 'kid-009',
      name: '儿童背景 9',
      category: 'kid',
      imageUrl: `${BACKGROUND_BASE_PATH}/kid/495203d6c5e4b0f75ba751167372361a.png`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/kid/495203d6c5e4b0f75ba751167372361a.jpg`,
    },
    {
      id: 'kid-010',
      name: '儿童背景 10',
      category: 'kid',
      imageUrl: `${BACKGROUND_BASE_PATH}/kid/6J6A3809.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/kid/6J6A3809.jpg`,
    },
    {
      id: 'kid-011',
      name: '儿童背景 11',
      category: 'kid',
      imageUrl: `${BACKGROUND_BASE_PATH}/kid/DSC00182.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/kid/DSC00182.jpg`,
    },
    {
      id: 'kid-012',
      name: '儿童背景 12',
      category: 'kid',
      imageUrl: `${BACKGROUND_BASE_PATH}/kid/DSC00305.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/kid/DSC00305.jpg`,
    },
    {
      id: 'kid-013',
      name: '儿童背景 13',
      category: 'kid',
      imageUrl: `${BACKGROUND_BASE_PATH}/kid/DSC06277.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/kid/DSC06277.jpg`,
    },
    {
      id: 'kid-014',
      name: '儿童背景 14',
      category: 'kid',
      imageUrl: `${BACKGROUND_BASE_PATH}/kid/DSC06987.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/kid/DSC06987.jpg`,
    },
    {
      id: 'kid-015',
      name: '儿童背景 15',
      category: 'kid',
      imageUrl: `${BACKGROUND_BASE_PATH}/kid/DSCF6641.jpg`,
      cleanBackgroundUrl: `${CLEAN_BACKGROUND_BASE_PATH}/kid/DSCF6641.jpg`,
    }
  ],
};

/**
 * 获取完整背景库
 */
export function getBackgroundLibrary(): BackgroundLibrary {
  return BACKGROUND_LIBRARY;
}

/**
 * 按分类获取背景列表
 */
export function getBackgroundsByCategory(category: BackgroundCategory): BackgroundPoseItem[] {
  return BACKGROUND_LIBRARY[category] || [];
}

/**
 * 按ID获取单个背景项
 */
export function getBackgroundById(id: string): BackgroundPoseItem | null {
  const all = [
    ...BACKGROUND_LIBRARY.girl,
    ...BACKGROUND_LIBRARY.boy,
    ...BACKGROUND_LIBRARY.kid
  ];
  return all.find(bg => bg.id === id) || null;
}

/**
 * 获取所有背景数量
 */
export function getBackgroundCounts(): Record<BackgroundCategory, number> {
  return {
    girl: BACKGROUND_LIBRARY.girl.length,
    boy: BACKGROUND_LIBRARY.boy.length,
    kid: BACKGROUND_LIBRARY.kid.length,
  };
}

/**
 * 获取随机背景
 */
export function getRandomBackground(category?: BackgroundCategory): BackgroundPoseItem | null {
  let pool: BackgroundPoseItem[];

  if (category) {
    pool = BACKGROUND_LIBRARY[category];
  } else {
    pool = [
      ...BACKGROUND_LIBRARY.girl,
      ...BACKGROUND_LIBRARY.boy,
      ...BACKGROUND_LIBRARY.kid
    ];
  }

  if (pool.length === 0) return null;
  return pool[Math.floor(Math.random() * pool.length)];
}
