/**
 * 生成完整的背景图库配置文件
 *
 * 运行: pnpm exec tsx scripts/generate-background-library.ts
 */

import * as fs from 'fs';
import * as path from 'path';

const BACKGROUNDS_DIR = path.join(__dirname, '../../../apps/virtual-tryon-demo/public/backgrounds');
const OUTPUT_FILE = path.join(__dirname, '../src/lib/backgroundLibrary.ts');

type Category = 'girl' | 'boy' | 'kid';

interface BackgroundItem {
  id: string;
  name: string;
  category: Category;
  filename: string;
  cleanFilename: string;
}

function getCleanFilename(filename: string): string {
  // 将扩展名统一转为小写 .jpg
  return filename.replace(/\.(JPG|JPEG|PNG|jpeg|png)$/i, '.jpg');
}

function generateItems(category: Category): BackgroundItem[] {
  const dir = path.join(BACKGROUNDS_DIR, category);
  const files = fs.readdirSync(dir).filter(f =>
    /\.(jpg|jpeg|png|JPG|JPEG|PNG)$/i.test(f)
  ).sort();

  return files.map((filename, index) => ({
    id: `${category}-${String(index + 1).padStart(3, '0')}`,
    name: `${category === 'girl' ? '女生' : category === 'boy' ? '男生' : '儿童'}背景 ${index + 1}`,
    category,
    filename,
    cleanFilename: getCleanFilename(filename),
  }));
}

function escapeString(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
}

function generateLibraryCode(): string {
  const girlItems = generateItems('girl');
  const boyItems = generateItems('boy');
  const kidItems = generateItems('kid');

  const generateItemsCode = (items: BackgroundItem[]): string => {
    return items.map(item => `    {
      id: '${item.id}',
      name: '${item.name}',
      category: '${item.category}',
      imageUrl: \`\${BACKGROUND_BASE_PATH}/${item.category}/${escapeString(item.filename)}\`,
      cleanBackgroundUrl: \`\${CLEAN_BACKGROUND_BASE_PATH}/${item.category}/${escapeString(item.cleanFilename)}\`,
    }`).join(',\n');
  };

  return `// Background Library Configuration for Virtual Try-On V2
// Auto-generated by scripts/generate-background-library.ts
// Total: ${girlItems.length + boyItems.length + kidItems.length} backgrounds (Girl: ${girlItems.length}, Boy: ${boyItems.length}, Kid: ${kidItems.length})

import type {
  BackgroundLibrary,
  BackgroundPoseItem,
  BackgroundCategory
} from '../types/background';

/**
 * 背景图片基础路径
 * 实际部署时需要将图片复制到 public/backgrounds 目录
 */
export const BACKGROUND_BASE_PATH = '/backgrounds';

/**
 * 干净背景（人物已移除）的基础路径
 * 用于 V3 单轮生成模式
 */
export const CLEAN_BACKGROUND_BASE_PATH = '/backgrounds-clean';

/**
 * 从原图URL生成干净背景URL
 * @param originalUrl 原图URL (e.g., '/backgrounds/girl/photo.jpg')
 * @returns 干净背景URL (e.g., '/backgrounds-clean/girl/photo.jpg')
 */
export function getCleanBackgroundUrl(originalUrl: string): string {
  // 将原图路径转换为干净背景路径，并统一使用 .jpg 扩展名
  return originalUrl
    .replace(BACKGROUND_BASE_PATH, CLEAN_BACKGROUND_BASE_PATH)
    .replace(/\\.(JPG|JPEG|PNG|jpeg|png)$/i, '.jpg');
}

/**
 * 静态背景库配置
 * 图片来源于 background&pose 文件夹
 */
export const BACKGROUND_LIBRARY: BackgroundLibrary = {
  girl: [
${generateItemsCode(girlItems)}
  ],
  boy: [
${generateItemsCode(boyItems)}
  ],
  kid: [
${generateItemsCode(kidItems)}
  ],
};

/**
 * 获取完整背景库
 */
export function getBackgroundLibrary(): BackgroundLibrary {
  return BACKGROUND_LIBRARY;
}

/**
 * 按分类获取背景列表
 */
export function getBackgroundsByCategory(category: BackgroundCategory): BackgroundPoseItem[] {
  return BACKGROUND_LIBRARY[category] || [];
}

/**
 * 按ID获取单个背景项
 */
export function getBackgroundById(id: string): BackgroundPoseItem | null {
  const all = [
    ...BACKGROUND_LIBRARY.girl,
    ...BACKGROUND_LIBRARY.boy,
    ...BACKGROUND_LIBRARY.kid
  ];
  return all.find(bg => bg.id === id) || null;
}

/**
 * 获取所有背景数量
 */
export function getBackgroundCounts(): Record<BackgroundCategory, number> {
  return {
    girl: BACKGROUND_LIBRARY.girl.length,
    boy: BACKGROUND_LIBRARY.boy.length,
    kid: BACKGROUND_LIBRARY.kid.length,
  };
}

/**
 * 获取随机背景
 */
export function getRandomBackground(category?: BackgroundCategory): BackgroundPoseItem | null {
  let pool: BackgroundPoseItem[];

  if (category) {
    pool = BACKGROUND_LIBRARY[category];
  } else {
    pool = [
      ...BACKGROUND_LIBRARY.girl,
      ...BACKGROUND_LIBRARY.boy,
      ...BACKGROUND_LIBRARY.kid
    ];
  }

  if (pool.length === 0) return null;
  return pool[Math.floor(Math.random() * pool.length)];
}
`;
}

// 执行生成
const code = generateLibraryCode();
fs.writeFileSync(OUTPUT_FILE, code, 'utf-8');
console.log(`Generated backgroundLibrary.ts with all backgrounds`);
console.log(`Output: ${OUTPUT_FILE}`);
